pipeline {
    agent { label 'my-label' }
    stages {
        stage('Clone') {
            steps {
                sshagent(['sshcredentials']) {
                    git branch: 'main',
                    credentialsId: 'sshcredentials',
                    url: 'https://github.com/UGUP/NodeApplication.git'
                }
            }
        }
    }
}
